"""initial_schema

Revision ID: 99b057afe1c1
Revises: 
Create Date: 2026-06-09 22:51:29.641475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b057afe1c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=True),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_id'), ['id'], unique=False)

    op.create_table('nutrition_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_day_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_nutrition_day_id'), ['id'], unique=False)

    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Integer(), nullable=False),
    sa.Column('fat_max_g', sa.Integer(), nullable=False),
    sa.Column('unit_system', sa.String(length=20), nullable=False),
    sa.Column('yazio_last_sync', sa.DateTime(), nullable=True),
    sa.Column('yazio_last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('asleep_minutes', sa.Integer(), nullable=False),
    sa.Column('in_bed_minutes', sa.Integer(), nullable=False),
    sa.Column('deep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_minutes', sa.Integer(), nullable=True),
    sa.Column('core_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_log_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_sleep_log_id'), ['id'], unique=False)

    op.create_table('steps_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_log_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_steps_log_id'), ['id'], unique=False)

    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_log_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_weight_log_id'), ['id'], unique=False)

    op.create_table('routine_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_rep_low', sa.Integer(), nullable=False),
    sa.Column('target_rep_high', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_exercise_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_exercise_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routine_exercise_routine_id'), ['routine_id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_started_at'), ['started_at'], unique=False)

    op.create_table('session_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_exercise_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercise_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_exercise_session_id'), ['session_id'], unique=False)

    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_session_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_set_id'))

    op.drop_table('set')
    with op.batch_alter_table('session_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_exercise_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_session_exercise_exercise_id'))

    op.drop_table('session_exercise')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_started_at'))
        batch_op.drop_index(batch_op.f('ix_session_routine_id'))
        batch_op.drop_index(batch_op.f('ix_session_id'))

    op.drop_table('session')
    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_exercise_routine_id'))
        batch_op.drop_index(batch_op.f('ix_routine_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_routine_exercise_exercise_id'))

    op.drop_table('routine_exercise')
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_log_id'))
        batch_op.drop_index(batch_op.f('ix_weight_log_date'))

    op.drop_table('weight_log')
    with op.batch_alter_table('steps_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_log_id'))
        batch_op.drop_index(batch_op.f('ix_steps_log_date'))

    op.drop_table('steps_log')
    with op.batch_alter_table('sleep_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_log_id'))
        batch_op.drop_index(batch_op.f('ix_sleep_log_date'))

    op.drop_table('sleep_log')
    op.drop_table('settings')
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_id'))

    op.drop_table('routine')
    with op.batch_alter_table('nutrition_day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_day_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_day_date'))

    op.drop_table('nutrition_day')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_id'))

    op.drop_table('exercise')
    # ### end Alembic commands ###
